#The file by CI Studio™
#作者：Entity
#灵感源于QQ用户“MEW小黑”的一句“监狱模拟器”
import random
class tc:
    rel = '\033[0m'
    yel = '\033[93m'
    blu = '\033[94m'
    red = '\033[91m'
name = "Mr.Fuck","Mr.Shit","Miss.Bitch","Miss.CNM","Mr.WDNMD","Miss.TankU","Mr.FaQ","Miss.NMD"
emote = "心情优","心情良好","心情一般","心情不好","心情暴怒","心情核平"
things = "故意杀人","袭警","走私违禁品","吸毒","围殴他人","滥职","网络暴力他人","传播谣言","纵火"
die = "被揍死了","放屁崩死了","心脏病复发死了","严重抑郁死了","自闭死了","撞墙死了","热死了","冻死了","被枪击死了","电死了","被刺死了","思念过度死了","叫死了","病死了","憋尿死了","拉屎痛死了","被踢小鸟(屁屁)痛死了","摔死了","掉入了虚空","自闭死了","老死了","旧病复发死了","窒息死了","被勒死了","身体虚弱死了","跑步猝死了","渐冻症死了","哮喘死了","熬夜死了","越狱跳海溺死了","溺水死了","打篮球被砸死了","微波炉铅板坏了被辐射死了","被踢死了","被骂死了","被笑话笑的肺泡炸裂死了","被♂死了"
time = random.randint(3,10)
RE = random.sample(emote,1)
rn = random.sample(name,1)
rt = random.sample(things,1)
rd = random.sample(die,1)
print(f'你叫{rn}，你已经成年了，因为你一时冲动，所以{rt}了')
if time <= 7:
    print(f'你被判了{time}年的有期徒刑')
else:
    if time >= 8:
        if time >= 9:
            if time == 10:
                print('你被判了死刑')
            else:
                print('你被判了死缓')
        else:
            print('你被判了无期徒刑')
print(f'第1天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第2天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第3天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第4天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第5天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第6天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第7天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第8天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第9天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第10天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第11天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第12天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第13天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第14天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第15天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第16天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第17天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第18天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第19天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第20天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第21天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第22天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第23天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第24天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第25天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第26天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第27天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第28天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第29天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第30天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第31天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第32天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第33天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第34天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第35天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第36天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第37天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第38天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第39天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第40天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第41天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第42天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第43天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第44天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第45天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第46天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第47天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第48天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第49天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第50天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第51天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第52天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第53天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第54天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第55天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第56天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第57天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第58天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第59天，你{RE}')
RE = random.sample(emote,1)
input()
print(f'第60天，你{RE}')
print(f'你{rd}')
input()